workflows:
  ios-workflow:
    name: iOS App Store Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    integrations:
      app_store_connect: Daily1 API Key
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.daily1.app
      vars:
        BUNDLE_ID: "com.daily1.app"
        APP_NAME: "Daily 1"
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "*.xcworkspace" \
            --scheme "*" \
            --archive-flags="-destination 'generic/platform=iOS'"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false
